name: instasend
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.7
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  geolocator: ^5.3.2+2
  uuid: ^2.0.0
  toast: ^0.1.5
  image: ^2.1.14
  animator: ^2.0.1
  path_provider: ^1.6.11
  flutter_spinkit: ^4.1.2+1
  persistent_bottom_nav_bar: ^2.0.5
  firebase_messaging: ^6.0.16
  timeago: ^2.0.26
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta.ttf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf

  assets:
    - assets/images/